<a href="https://colab.research.google.com/github/daibacgantay/consumption-in-business/blob/main/Data_Processing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [24]:
# Load libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

### **Overview of Data**

In [25]:
#Read the data file
df = pd.read_excel(r'/content/drive/MyDrive/Junior-1/Sale-data.xlsx')

In [26]:
# Drop all the uneccessary column
data_use = df.drop(['Thang', 'TotalRevenue', 'TotalProfit', '%Doanh Thu', '%LoiNhuan', 'Ship Date', 'Ship Mode', 'Order Priority', 'Customer Name', 'City', 'State', 'Months', 'Discount' ], axis=1)

In [27]:
#View all the data
data_use.head()

,Order ID,Order Date,Aging,Product Category,Product,Price,Revenue,Quantity,Discount_Value,Profit,Shipping Cost,Customer ID,Segment,Country,Region
0,AU-2015-172,42005,8,Auto & Accessories,Car Media Players,140,564.880,4,11.20,48.80,4.880,HY-00172,Consumer,Mexico,North
1,AU-2015-1473,42005,7,Auto & Accessories,Bike Tyres,72,361.440,5,7.20,14.40,1.440,NI-001473,Consumer,South Korea,North Asia
2,AU-2015-1650,42005,10,Auto & Accessories,Car Body Covers,117,587.530,5,11.70,25.30,2.530,UM-001650,Home Office,South Africa,Africa
3,AU-2015-1999,42005,8,Auto & Accessories,Car Media Players,140,564.880,4,11.20,48.80,4.880,CK-001999,Consumer,Turkey,EMEA
4,AU-2015-2155,42005,10,Auto & Accessories,Car & Bike Care,118,357.092,3,7.08,30.92,3.092,LD-002155,Home Office,Mexico,North

In [28]:
#Shape of data
print(data_use.shape)

(51290, 15)

In [29]:
#Summary about the structure of Data
# All column is enough, therefore, we dont need to remove any null value
data_use.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51290 entries, 0 to 51289
Data columns (total 15 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Order ID          51290 non-null  object
 1   Order Date        51290 non-null  int64
 2   Aging             51290 non-null  int64
 3   Product Category  51290 non-null  object
 4   Product           51290 non-null  object
 5   Price             51290 non-null  int64
 6   Revenue           51290 non-null  float64
 7   Quantity          51290 non-null  int64
 8   Discount_Value    51290 non-null  float64
 9   Profit            51290 non-null  float64
 10  Shipping Cost     51290 non-null  float64
 11  Customer ID       51290 non-null  object
 12  Segment           51290 non-null  object
 13  Country           51290 non-null  object
 14  Region            51290 non-null  object
dtypes: float64(4), int64(4), object(7)
memory usage: 5.9+ MB

###**Create the new columns**

In [30]:
region = data_use["Region"]

In [31]:
data_use['Region_country'] = region

In [32]:
data_use['longitude'] = region

In [33]:
data_use['latitude'] = region

In [34]:
data_use['geo'] = region

### **Process data : Map the correct region to each other. Add latitude and longtitude of each region and geomtry of each country**

In [35]:
mygeo = {
    'Albania': '40.64655281641075,20.167427858529976',#
    'Afghanistan': '33.830488723632016,66.03138202616762',#
    'Algeria':'27.812233010519165,2.5694220562197643',#
    'Angola': '-12.155817791902194,17.886557859291912',#
    'Argentina': '-36.43447998864781,-64.08401167139661',#
    'Armenia': '40.60408484397257,44.65966977686105',#
    'Australia': '-25.944567618224113,134.45363390598288',#
    'Austria' : '47.61384655959853,14.289484199209454',#
    'Azerbaijan': '40.33489925305145,47.77815682907507',
    'Bahrain': '26.022900073007165,50.560739841135614',
    'Bangladesh': '24.142964320707932,90.03788879989213',#
    'Barbados': '13.174091171229122,-59.56129049451815',
    'Belarus': '53.510466238293105,28.049062078618533',
    'Belgium': '50.58216779951192,4.973353937363271',#
    'Benin': '10.103767094732845,2.3322100960558316',
    'Bolivia': '-17.188957860661205,-64.37622882663047',
    'Bosnia and Herzegovina': '44.24038662640058,17.706221833217455',
    'Brazil': '-10.224415427659778,-51.694986613902586',#
    'Bulgaria': '42.62661039221595,24.55981105090828',
    'Burundi': '-3.5426146636116442,29.876949783076213',
    'Cambodia': '12.313842060184001,104.798847316572',
    'Cameroon': '4.924216750835029,12.151432369680833',
    'Canada':'55.299627123352906,-105.29607230485846',
    'Central African Republic': '-26.028133322477885,27.936374963287733',
    'Chad':'15.105481440362865,18.56134629543726',
    'Chile':'-27.174721457965134,-69.76874819228635',
    'China':'35.39923866973736,101.58457891554997',
    'Colombia':'2.6006071097139767,-73.1384013424513',
    "Cote d'Ivoire": '-26.10120362695276,28.116740575606258',
    'Croatia': '45.631279751101204,16.79656767877438',
    'Cuba': '21.93538523660898,-79.32854252817',
    'Czech Republic': '49.73105120921343,15.323487124541657',
    'Democratic Republic of the Congo': '-1.2632509884075347,23.212524442311405',
    'Denmark':'55.83488930923332,9.714045459779356',
    'Djibouti':'11.718741566066612,42.44289377609272',
    'Dominican Republic': '19.068158229993514,-70.49837445153588',
    'Ecuador': '-1.4437982469896724,-78.43711600728265',
    'Egypt': '25.873112964434256,29.660697546473358',
    'El Salvador': '13.715987278227544,-88.86254594748813',
    'Equatorial Guinea': '1.6136981355075335,10.437111116628529',
    'Eritrea': '15.676250705897871,38.55609688813195',
    'Estonia': '58.7476896711112,25.697965747143627',
    'Ethiopia': '8.64513208470106,39.57860528634126',
    'Finland': '62.494268755358036,25.899174284668476',
    'France' : '47.49904156564784,2.3591597818098933',
    'Gabon' : '-0.7132251241093428,11.861310025895392',
    'Georgia': '42.08649441163419,43.39812154939605',
    'Germany': '50.866953479265305,9.815645873171604',#
    'Ghana': '6.577461759019073,-1.1937542034081332',
    'Guadeloupe': '20.135913135099187,-75.26088976280346',
    'Guatemala': '15.547545785810229,-90.34456439612751',#Central America
    'Guinea': '1.6136981355075335,10.437111116628529',
    'Guinea-Bissau': '1.6136981355075335,10.437111116628529',
    'Haiti': '19.140651560319654,-72.26895629997571',
    'Honduras': '14.711903724525044,-86.91813518647876',
    'Hong Kong': '22.27675330109544,114.13917331715584',
    'Hungary': '46.98503005720099,19.333219537210994',
    'India': '22.043515581445988,78.45262976345424',
    'Indonesia': '0.6440669230172773, 114.9502877530993',
    'Iran': '32.49412430073059,54.12049070666109',
    'Iraq': '32.92526328472876,43.25095537276445',
    'Ireland': '53.23880424242941,-7.957354560108826',
    'Israel': '31.852581217190874,34.81870567827772',
    'Italy': '42.31065603023214,12.804470456588888',
    'Jamaica': '18.15819395247749,-77.34486793625041',
    'Japan': '36.064487317997376,138.55732100751612',#
    'Jordan': '31.07594829408704,36.53861181032104',
    'Kazakhstan': '47.65812769960354,67.3673620265547',
    'Kenya': '0.10346247640687523,37.81672197708602',
    'Kyrgyzstan':'41.32191745074286,74.47312836445994',
    'Lebanon':'33.94428302058296,35.78554822577132',
    'Lesotho':'-29.697058646301656,28.234330422381277',
    'Liberia': '6.310610952075265,-9.396857257296432',
    'Libya': '26.877670003135222,18.012268812198585',
    'Lithuania': '55.412959955123085,23.869542086350066',
    'Macedonia': '41.55967790801017,21.55053044137668',
    'Madagascar': '-19.718219600432718,46.73540325751682',
    'Malaysia': '4.302663379782999,102.11216255562772',
    'Mali': '17.15417566210911,-1.3962115723962825',
    'Martinique': '14.627718958017297,-60.96267203170186',
    'Mauritania': '19.736283802532142,-10.438431988823652',
    'Mexico': '23.597460394666513,-102.51749393440099',
    'Moldova':'47.043810566013775,28.468827997861013',
    'Mongolia': '46.406838186852156,103.72495782090436',#
    'Montenegro': '42.77549387244852,19.322524687018557',
    'Morocco': '32.335215132561075,-6.199144653799181',
    'Mozambique': '-18.1323445042985,34.80117328300173',
    'Myanmar (Burma)': '21.18420382703961,96.54819247667729',
    'Namibia': '-22.19296896377348,17.109033997543435',
    'Nepal': '28.22516550579674,83.77261417271512',
    'Netherlands': '51.95860145907386,5.168093741619231',
    'New Zealand': '-41.90575378102264,172.31502752249366',
    'Nicaragua': '12.153211042375375,-84.85435270546408',
    'Niger':'17.39516239485758,9.08382838495939',
    'Nigeria': '9.829258793695075,8.006735476282302',
    'Norway': '61.001265372916635,9.351235541471112',
    'Pakistan': '27.977191481125104,68.07483250826988',
    'Panama': '8.610802215458989,-80.76294333491258',
    'Papua New Guinea': '-5.774710309609972,143.75248796942412',
    'Paraguay': '-23.39873027503036,-58.206865075960906',
    'Peru': '-10.288864814724363,-74.79537749271657',
    'Philippines': '11.59987280477641,122.57172743432682',
    'Poland': '52.15099949935458,19.28159695441093',
    'Portugal': '39.52647756806499,-8.33249396071642',
    'Qatar': '25.23050793860233,50.97308835412542',
    'Republic of the Congo': '-0.3038420091040024,16.013719808898003',
    'Romania': '45.59150057909659,25.019076225246863',
    'Russia': '55.72525993643592,37.62771267067123',
    'Rwanda': '-1.8517463255688682,29.861527558298576',
    'Saudi Arabia': '22.94111049394823,44.59986808192656',
    'Senegal': '15.213696849881742,-15.58766529263383',
    'Sierra Leone': '8.45900567697015,-11.797495833864645',
    'Singapore': '1.3563200603857837,103.82246622979466',
    'Slovakia': '48.65674039714233,19.493753052933585',
    'Slovenia': '46.13872158271414,14.583912242067129',
    'Somalia': '5.771759435379465,47.33410718600021',
    'South Africa': '-28.635418518916147,23.98883394282896',
    'South Korea': '36.60535319943733,127.7942888349379',
    'South Sudan': '7.375356261276053,30.375382634737235',
    'Spain': '40.91610655586237,-3.9264389006035003',
    'Sri Lanka': '7.408158185687,80.82434849336084',
    'Sudan': '13.641136599541056,29.946228310227355',
    'Swaziland': '-26.61899049015144,31.49308106072789',
    'Sweden': '64.47376969588262,17.105728747102972',
    'Switzerland': '46.762210006511594,7.9742534977291655',
    'Syria': '34.86897828875156,38.52181325939861',
    'Taiwan': '23.6470571901919,121.02013688764794',
    'Tajikistan': '38.950402395513265,71.09439786627672',
    'Tanzania': '-6.4769905765836455,35.398663156379484',
    'Thailand': '15.011898151701246,101.27653380532996',
    'Togo': '8.770155258448895,1.02219304653147',
    'Trinidad and Tobago': '10.407071490021451, -61.25068812305361',
    'Tunisia': '34.112464383328586,9.555128260957304',
    'Turkey': '38.925913017951416,35.284843732445836',
    'Turkmenistan': '38.83372375524755,59.1447875092735',
    'Uganda': '1.2672995146643586,32.41846179676716',
    'Ukraine': '49.21146616692326,31.287291654664244', #Europe
    'United Arab Emirates': '23.83921558081049,54.23679274787506',
    'United Kingdom': ' 54.046023059660456,-1.9504255421663572',
    'United States': '39.033956525080185,-98.20851957850579',
    'Uruguay': '-32.86394629004666,-55.98027203507806',
    'Uzbekistan': '41.69981260703503,63.56649366605211',
    'Venezuela': '7.207546278589035,-65.85406773730307',
    'Vietnam': '14.276000216720362,108.11110183162606',
    'Yemen': '15.996250762510329,47.81003316042887',
    'Zambia': '-14.385206500174448,27.26672130362465',
    'Zimbabwe': '-19.554765907498137,30.132193217620028'
}

In [36]:
mydic = {
    'Albania': 'Europe',
    'Afghanistan': 'Asia',
    'Algeria':'Africa',
    'Angola': 'Africa',
    'Argentina': 'South America',
    'Armenia': 'Caucasus',
    'Australia': 'Australia',#Doi
    'Austria' : 'Europe',
    'Azerbaijan': 'Caucasus',
    'Bahrain': 'Middle East',
    'Bangladesh': 'Asia',
    'Barbados': 'Caribbean',
    'Belarus': 'Europe',
    'Belgium': 'Europe',
    'Benin': 'Africa',
    'Bolivia': 'South America',
    'Bosnia and Herzegovina': 'Europe',
    'Brazil': 'South America',
    'Bulgaria': 'Europe',
    'Burundi': 'Africa',
    'Cambodia': 'Asia',
    'Cameroon': 'Africa',
    'Canada':'North America',
    'Central African Republic': 'Africa',
    'Chad':'Africa',
    'Chile':'South America',
    'China':'Asia',
    'Colombia':'South America',
    "Cote d'Ivoire": 'Africa',
    'Croatia': 'Europe',
    'Cuba': 'Caribbean',
    'Czech Republic': 'Europe',
    'Democratic Republic of the Congo': 'Africa',
    'Denmark':'Europe',
    'Djibouti':'Africa',
    'Dominican Republic': 'Caribbean',
    'Ecuador': 'South America',
    'Egypt': 'Africa',
    'El Salvador': 'Central America',
    'Equatorial Guinea': 'Africa',
    'Eritrea': 'Africa',
    'Estonia': 'Europe',
    'Ethiopia': 'Africa',
    'Finland': 'Europe',
    'France' : 'Europe',
    'Gabon' : 'Africa',
    'Georgia': 'Caucasus',
    'Germany': 'Europe',
    'Ghana': 'Africa',
    'Guadeloupe': 'Caribbean',
    'Guatemala': 'Central America',
    'Guinea': 'Africa',
    'Guinea-Bissau': 'Africa',
    'Haiti': 'Caribbean',
    'Honduras': 'South America',
    'Hong Kong': 'Asia',
    'Hungary': 'Europe',
    'India': 'Asia',
    'Indonesia': 'Asia',
    'Iran': 'Middle East',
    'Iraq': 'Middle East',
    'Ireland': 'Europe',
    'Israel': 'Middle East',
    'Italy': 'Europe',
    'Jamaica': 'Caribbean',
    'Japan': 'Asia',
    'Jordan': 'Middle East',
    'Kazakhstan': 'Asia',
    'Kenya': 'Africa',
    'Kyrgyzstan':'Asia',
    'Lebanon':'Middle East',
    'Lesotho':'Africa',
    'Liberia': 'Africa',
    'Libya': 'Africa',
    'Lithuania': 'Europe',
    'Macedonia': 'Europe',
    'Madagascar': 'Europe',
    'Malaysia': 'Asia',
    'Mali': 'Africa',
    'Martinique': 'Caribbean',
    'Mauritania': 'Africa',
    'Mexico': 'North America',
    'Moldova':'Europe',
    'Mongolia': 'Asia',
    'Montenegro': 'Europe',
    'Morocco': 'Africa',
    'Mozambique': 'Africa',
    'Myanmar (Burma)': 'Asia',
    'Namibia': 'Africa',
    'Nepal': 'Asia',
    'Netherlands': 'Europe',
    'New Zealand': 'New Zealand',#Doi
    'Nicaragua': 'South America',
    'Niger':'Africa',
    'Nigeria': 'Africa',
    'Norway': 'Europe',
    'Pakistan': 'Asia',
    'Panama': 'South America',
    'Papua New Guinea': 'Papua New Guinea',#Doi
    'Paraguay': 'South America',
    'Peru': 'South America',
    'Philippines': 'Asia',
    'Poland': 'Europe',
    'Portugal': 'Europe',
    'Qatar': 'Middle East',
    'Republic of the Congo': 'Africa',
    'Romania': 'Europe',
    'Russia': 'Europe',
    'Rwanda': 'Africa',
    'Saudi Arabia': 'Middle East',
    'Senegal': 'Africa',
    'Sierra Leone': 'Africa',
    'Singapore': 'Asia',
    'Slovakia': 'Europe',
    'Slovenia': 'Europe',
    'Somalia': 'Africa',
    'South Africa': 'Africa',
    'South Korea': 'Asia',
    'South Sudan': 'Africa',
    'Spain': 'Europe',
    'Sri Lanka': 'Asia',
    'Sudan': 'Africa',
    'Swaziland': 'Africa',
    'Sweden': 'Europe',
    'Switzerland': 'Europe',
    'Syria': 'Middle East',
    'Taiwan': 'Asia',
    'Tajikistan': 'Asia',
    'Tanzania': 'Africa',
    'Thailand': 'Asia',
    'Togo': 'Africa',
    'Trinidad and Tobago': 'Caribbean',
    'Tunisia': 'Africa',
    'Turkey': 'Asia',
    'Turkmenistan': 'Asia',
    'Uganda': 'Africa',
    'Ukraine': 'Europe',
    'United Arab Emirates': 'Middle East',
    'United Kingdom': 'Europe',
    'United States': 'North America',
    'Uruguay': 'South America',
    'Uzbekistan': 'Asia',
    'Venezuela': 'South America',
    'Vietnam': 'Asia',
    'Yemen': 'Middle East',
    'Zambia': 'Africa',
    'Zimbabwe': 'Africa'


}

In [37]:
for k,v in mydic.items():
  data_use['Region_country'].mask(df['Country'] == k, v, inplace=True)

In [38]:
mylong = {
    'Central America': '-85.602364',
    'North America': '-100.166666',
    'South America': '-55.491477',
    'Asia': '100.619655',
    'Africa': '34.50852299999997',
    'Europe':'14.4002',
    'Middle East': '39.7332',
    'Caribbean': '-75.818333',
    'Papua New Guinea': '143.9555',
    'Australia': '133.281323',
    'New Zealand': '172.4662705',
    'Caucasus': '44.119332856'

}

In [39]:
for k,v in mylong.items():
  data_use['longitude'].mask(data_use['Region_country'] == k, v, inplace=True)

In [40]:
mylat = {
    'Central America': '12.769013',
    'North America': '48.166666',
    'South America': '-8.783195',
    'Asia': '34.047863',
    'Africa': '-8.783195',
    'Europe':'50.0902',
    'Middle East': '30.5852',
    'Caribbean': '14.525556',
    'Papua New Guinea': '-6.31555',
    'Australia': '-26.4390917',
    'New Zealand': '-43.3744881',
    'Caucasus': '42.25666564'

}

In [41]:
for k,v in mylat.items():
  data_use['latitude'].mask(data_use['Region_country'] == k, v, inplace=True)

In [42]:
for k,v in mygeo.items():
  data_use['geo'].mask(data_use['Country'] == k, v, inplace=True)

In [43]:
country = data_use['Country']

In [44]:
 #Now, let's see the data again
data_use.head()

,Order ID,Order Date,Aging,Product Category,Product,Price,Revenue,Quantity,Discount_Value,Profit,Shipping Cost,Customer ID,Segment,Country,Region,Region_country,longitude,latitude,geo
0,AU-2015-172,42005,8,Auto & Accessories,Car Media Players,140,564.880,4,11.20,48.80,4.880,HY-00172,Consumer,Mexico,North,North America,-100.166666,48.166666,"23.597460394666513,-102.51749393440099"
1,AU-2015-1473,42005,7,Auto & Accessories,Bike Tyres,72,361.440,5,7.20,14.40,1.440,NI-001473,Consumer,South Korea,North Asia,Asia,100.619655,34.047863,"36.60535319943733,127.7942888349379"
2,AU-2015-1650,42005,10,Auto & Accessories,Car Body Covers,117,587.530,5,11.70,25.30,2.530,UM-001650,Home Office,South Africa,Africa,Africa,34.50852299999997,-8.783195,"-28.635418518916147,23.98883394282896"
3,AU-2015-1999,42005,8,Auto & Accessories,Car Media Players,140,564.880,4,11.20,48.80,4.880,CK-001999,Consumer,Turkey,EMEA,Asia,100.619655,34.047863,"38.925913017951416,35.284843732445836"
4,AU-2015-2155,42005,10,Auto & Accessories,Car & Bike Care,118,357.092,3,7.08,30.92,3.092,LD-002155,Home Office,Mexico,North,North America,-100.166666,48.166666,"23.597460394666513,-102.51749393440099"

In [45]:
#Create new file including clean Data for Code web
data_use.to_excel("data_use_for_web.xlsx")